INHERIT: mkdocs-base.yaml

site_name: "Dynatrace Enablement Lab: Openpipeline Segments Iam"
repo_name: "View Code on GitHub"
repo_url: "https://github.com/dynatrace-wwse/enablement-openpipeline-segments-iam"
nav:
  - "1. About": index.md
