---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubeaudit
  namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}"
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeaudit-namespaces-${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}
subjects:
  - kind: ServiceAccount
    name: kubeaudit
    namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeaudit-namespaces
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeaudit
  namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}"
subjects:
  - kind: ServiceAccount
    name: kubeaudit
    namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubeaudit
---
apiVersion: batch/v1
kind: Job
metadata:
  name: kubeaudit
  namespace: "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}"
  annotations:
    argocd.argoproj.io/hook: PostSync
    #argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      serviceAccountName: kubeaudit
      restartPolicy: OnFailure
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: kubeaudit
          image: shopify/kubeaudit:v0.11
          args: ["all", "--exitcode", "0", "--namespace", "${{ values.projectName}}-${{ values.teamIdentifier }}-${{ values.releaseStage}}"]
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["all"]
            privileged: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true